// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace HighFive.Server.Specs.Features.Metrics
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Weekly Corporate Trends", Description="\tIn order to understand recogntion trends\r\n\tAs a user\r\n\tI want to be able to view" +
        " the total recognitions created for our company for the week \r\n\tgrouped by corpo" +
        "rate values", SourceFile="Features\\Metrics\\WeekCorpTrend.feature", SourceLine=0)]
    public partial class WeeklyCorporateTrendsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "WeekCorpTrend.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Weekly Corporate Trends", "\tIn order to understand recogntion trends\r\n\tAs a user\r\n\tI want to be able to view" +
                    " the total recognitions created for our company for the week \r\n\tgrouped by corpo" +
                    "rate values", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Zero recognitions created this week", new string[] {
                "F1-62"}, SourceLine=7)]
        public virtual void ZeroRecognitionsCreatedThisWeek()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Zero recognitions created this week", new string[] {
                        "F1-62"});
#line 8
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "CorporateValue",
                        "Count",
                        "DateCreated"});
#line 9
 testRunner.Given("There are 0 recognitions in the database", ((string)(null)), table1, "Given ");
#line 11
 testRunner.When("I look at the weekly ring", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
 testRunner.Then("I will see 0 recognitions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("10 recognitions this week", new string[] {
                "F1-62"}, SourceLine=14)]
        public virtual void _10RecognitionsThisWeek()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("10 recognitions this week", new string[] {
                        "F1-62"});
#line 15
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "CorporateValue",
                        "Count",
                        "DateCreated"});
            table2.AddRow(new string[] {
                        "Commitment",
                        "4",
                        "last seven days"});
            table2.AddRow(new string[] {
                        "Courage",
                        "5",
                        "last seven days"});
            table2.AddRow(new string[] {
                        "Excellence",
                        "6",
                        "last seven days"});
#line 16
 testRunner.Given("The following data in the database", ((string)(null)), table2, "Given ");
#line 21
 testRunner.When("I look at the weekly ring", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "CorporateValue",
                        "Count"});
            table3.AddRow(new string[] {
                        "Commitment",
                        "4"});
            table3.AddRow(new string[] {
                        "Courage",
                        "5"});
            table3.AddRow(new string[] {
                        "Excellence",
                        "6"});
#line 22
 testRunner.Then("I will see donut slices representing 15 total recognitions with the following dat" +
                    "a", ((string)(null)), table3, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class WeeklyCorporateTrendsFeature_MsTest
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "WeekCorpTrend.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Weekly Corporate Trends", "\tIn order to understand recogntion trends\r\n\tAs a user\r\n\tI want to be able to view" +
                    " the total recognitions created for our company for the week \r\n\tgrouped by corpo" +
                    "rate values", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "Weekly Corporate Trends")))
            {
                HighFive.Server.Specs.Features.Metrics.WeeklyCorporateTrendsFeature_MsTest.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Zero recognitions created this week")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Weekly Corporate Trends")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("F1-62")]
        public virtual void ZeroRecognitionsCreatedThisWeek()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Zero recognitions created this week", new string[] {
                        "F1-62"});
#line 8
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "CorporateValue",
                        "Count",
                        "DateCreated"});
#line 9
 testRunner.Given("There are 0 recognitions in the database", ((string)(null)), table1, "Given ");
#line 11
 testRunner.When("I look at the weekly ring", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
 testRunner.Then("I will see 0 recognitions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("10 recognitions this week")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Weekly Corporate Trends")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("F1-62")]
        public virtual void _10RecognitionsThisWeek()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("10 recognitions this week", new string[] {
                        "F1-62"});
#line 15
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "CorporateValue",
                        "Count",
                        "DateCreated"});
            table2.AddRow(new string[] {
                        "Commitment",
                        "4",
                        "last seven days"});
            table2.AddRow(new string[] {
                        "Courage",
                        "5",
                        "last seven days"});
            table2.AddRow(new string[] {
                        "Excellence",
                        "6",
                        "last seven days"});
#line 16
 testRunner.Given("The following data in the database", ((string)(null)), table2, "Given ");
#line 21
 testRunner.When("I look at the weekly ring", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "CorporateValue",
                        "Count"});
            table3.AddRow(new string[] {
                        "Commitment",
                        "4"});
            table3.AddRow(new string[] {
                        "Courage",
                        "5"});
            table3.AddRow(new string[] {
                        "Excellence",
                        "6"});
#line 22
 testRunner.Then("I will see donut slices representing 15 total recognitions with the following dat" +
                    "a", ((string)(null)), table3, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
