// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace HighFive.Server.Specs.Features.Recognitions
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("CreateRecognition", Description="\tIn order to recognize a co-worker \r\n\tAs a user\r\n\tI want to input my feedback", SourceFile="Features\\Recognitions\\CreateRecognition.feature", SourceLine=0)]
    public partial class CreateRecognitionFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CreateRecognition.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CreateRecognition", "\tIn order to recognize a co-worker \r\n\tAs a user\r\n\tI want to input my feedback", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("F-13 Successfully create a recognition for an existing user", SourceLine=5)]
        public virtual void F_13SuccessfullyCreateARecognitionForAnExistingUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("F-13 Successfully create a recognition for an existing user", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "First Name",
                        "Last Name",
                        "Email",
                        "Organization Name",
                        "Password"});
            table1.AddRow(new string[] {
                        "Joe",
                        "Blow",
                        "joe.blow@email.com",
                        "Ariel Partners",
                        "password"});
#line 7
 testRunner.Given("I am logged in as the following user:", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Sender Email",
                        "Receiver Email",
                        "Organization Name",
                        "CorporateValue Name",
                        "Points",
                        "Description"});
            table2.AddRow(new string[] {
                        "joe.blow@email.com",
                        "suresh.nikam@email.com",
                        "Ariel Partners",
                        "Integrity",
                        "1",
                        "Great job!"});
#line 10
 testRunner.When("I create the following recognition:", ((string)(null)), table2, "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Sender Email",
                        "Receiver Email",
                        "Organization Name",
                        "CorporateValue Name",
                        "Points",
                        "Description"});
            table3.AddRow(new string[] {
                        "joe.blow@email.com",
                        "suresh.nikam@email.com",
                        "Ariel Partners",
                        "Integrity",
                        "1",
                        "Great job!"});
#line 13
 testRunner.Then("the system should confirm that the following recognition has been created:", ((string)(null)), table3, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("F-7 Successfully create a recognition for a new user", SourceLine=16)]
        public virtual void F_7SuccessfullyCreateARecognitionForANewUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("F-7 Successfully create a recognition for a new user", ((string[])(null)));
#line 17
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "First Name",
                        "Last Name",
                        "Email",
                        "Organization Name",
                        "Password"});
            table4.AddRow(new string[] {
                        "Joe",
                        "Blow",
                        "joe.blow@email.com",
                        "Ariel Partners",
                        "password"});
#line 18
 testRunner.Given("I am logged in as the following user:", ((string)(null)), table4, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Email"});
            table5.AddRow(new string[] {
                        "John Smith",
                        "john.smith@email.com"});
#line 21
 testRunner.And("the following user does not exist:", ((string)(null)), table5, "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Sender Email",
                        "New User Email",
                        "New User Name",
                        "Organization Name",
                        "CorporateValue Name",
                        "Points",
                        "Description"});
            table6.AddRow(new string[] {
                        "joe.blow@email.com",
                        "john.smith@email.com",
                        "John Smith",
                        "Ariel Partners",
                        "Integrity",
                        "1",
                        "Great job!"});
#line 24
 testRunner.When("I create the following recognition:", ((string)(null)), table6, "When ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Sender Email",
                        "Receiver Email",
                        "Organization Name",
                        "CorporateValue Name",
                        "Points",
                        "Description"});
            table7.AddRow(new string[] {
                        "joe.blow@email.com",
                        "john.smith@email.com",
                        "Ariel Partners",
                        "Integrity",
                        "1",
                        "Great job!"});
#line 27
 testRunner.Then("the system should confirm that the following recognition has been created:", ((string)(null)), table7, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name"});
            table8.AddRow(new string[] {
                        "john.smith@email.com",
                        "John Smith"});
#line 30
 testRunner.And("the following user should exist:", ((string)(null)), table8, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class CreateRecognitionFeature_MsTest
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CreateRecognition.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CreateRecognition", "\tIn order to recognize a co-worker \r\n\tAs a user\r\n\tI want to input my feedback", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "CreateRecognition")))
            {
                HighFive.Server.Specs.Features.Recognitions.CreateRecognitionFeature_MsTest.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("F-13 Successfully create a recognition for an existing user")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CreateRecognition")]
        public virtual void F_13SuccessfullyCreateARecognitionForAnExistingUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("F-13 Successfully create a recognition for an existing user", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "First Name",
                        "Last Name",
                        "Email",
                        "Organization Name",
                        "Password"});
            table1.AddRow(new string[] {
                        "Joe",
                        "Blow",
                        "joe.blow@email.com",
                        "Ariel Partners",
                        "password"});
#line 7
 testRunner.Given("I am logged in as the following user:", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Sender Email",
                        "Receiver Email",
                        "Organization Name",
                        "CorporateValue Name",
                        "Points",
                        "Description"});
            table2.AddRow(new string[] {
                        "joe.blow@email.com",
                        "suresh.nikam@email.com",
                        "Ariel Partners",
                        "Integrity",
                        "1",
                        "Great job!"});
#line 10
 testRunner.When("I create the following recognition:", ((string)(null)), table2, "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Sender Email",
                        "Receiver Email",
                        "Organization Name",
                        "CorporateValue Name",
                        "Points",
                        "Description"});
            table3.AddRow(new string[] {
                        "joe.blow@email.com",
                        "suresh.nikam@email.com",
                        "Ariel Partners",
                        "Integrity",
                        "1",
                        "Great job!"});
#line 13
 testRunner.Then("the system should confirm that the following recognition has been created:", ((string)(null)), table3, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("F-7 Successfully create a recognition for a new user")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CreateRecognition")]
        public virtual void F_7SuccessfullyCreateARecognitionForANewUser()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("F-7 Successfully create a recognition for a new user", ((string[])(null)));
#line 17
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "First Name",
                        "Last Name",
                        "Email",
                        "Organization Name",
                        "Password"});
            table4.AddRow(new string[] {
                        "Joe",
                        "Blow",
                        "joe.blow@email.com",
                        "Ariel Partners",
                        "password"});
#line 18
 testRunner.Given("I am logged in as the following user:", ((string)(null)), table4, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Email"});
            table5.AddRow(new string[] {
                        "John Smith",
                        "john.smith@email.com"});
#line 21
 testRunner.And("the following user does not exist:", ((string)(null)), table5, "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Sender Email",
                        "New User Email",
                        "New User Name",
                        "Organization Name",
                        "CorporateValue Name",
                        "Points",
                        "Description"});
            table6.AddRow(new string[] {
                        "joe.blow@email.com",
                        "john.smith@email.com",
                        "John Smith",
                        "Ariel Partners",
                        "Integrity",
                        "1",
                        "Great job!"});
#line 24
 testRunner.When("I create the following recognition:", ((string)(null)), table6, "When ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Sender Email",
                        "Receiver Email",
                        "Organization Name",
                        "CorporateValue Name",
                        "Points",
                        "Description"});
            table7.AddRow(new string[] {
                        "joe.blow@email.com",
                        "john.smith@email.com",
                        "Ariel Partners",
                        "Integrity",
                        "1",
                        "Great job!"});
#line 27
 testRunner.Then("the system should confirm that the following recognition has been created:", ((string)(null)), table7, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Name"});
            table8.AddRow(new string[] {
                        "john.smith@email.com",
                        "John Smith"});
#line 30
 testRunner.And("the following user should exist:", ((string)(null)), table8, "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
